# Livestreaming
* [Livestreaming](https://en.wikipedia.org/wiki/Livestreaming)
* [Comparison of the 15 Best Live Streaming Software](https://www.dacast.com/blog/live-broadcasting-software/)
  * [Wirecast](https://en.wikipedia.org/wiki/Wirecast)
  * [vMix](https://en.wikipedia.org/wiki/VMix)
  * [VidBlasterX](https://www.vidblasterx.com/)
  * [OBS Studio](https://en.wikipedia.org/wiki/OBS_Studio)
  * [Streamlabs](https://en.wikipedia.org/wiki/Streamlabs)
  * [FFmpeg](https://en.wikipedia.org/wiki/FFmpeg)
  * [XSplit](https://en.wikipedia.org/wiki/XSplit)
  * [SplitCam](https://splitcamera.com/)
  * [Switchboard Live](https://switchboard.live/)
  * [FFsplit](https://www.ffsplit.com/)
  * [PRISM Live Studio](https://prismlive.com/)
  * [OpenShot](https://en.wikipedia.org/wiki/OpenShot)
  * [FXhome](https://fxhome.com/)
  * [Restream](https://restream.io/)
  * [Dacast](https://en.wikipedia.org/wiki/Dacast)
* [Real-Time Messaging Protocol](https://en.wikipedia.org/wiki/Real-Time_Messaging_Protocol) (RTMP)
* [Network Device Interface](https://en.wikipedia.org/wiki/Network_Device_Interface) (NDI)
* [Video capture](https://en.wikipedia.org/wiki/Video_capture)
* [Justin Brown Primal Video](https://www.youtube.com/c/Primalvideo/videos)
